// Generated by Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import AppFriendsCore;
@import SlackTextViewController;
@import Foundation;
@import CoreGraphics;
@import AVFoundation;
@import CoreData;
@import CLTokenInputView;
@import SESlideTableViewCell;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSError;

SWIFT_CLASS("_TtC12AppFriendsUI12AppFriendsUI")
@interface AppFriendsUI : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AppFriendsUI * _Nonnull sharedInstance;)
+ (AppFriendsUI * _Nonnull)sharedInstance;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kDialogUpdateNotification;)
+ (NSString * _Nonnull)kDialogUpdateNotification;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kTotalUnreadMessageCountChangedNotification;)
+ (NSString * _Nonnull)kTotalUnreadMessageCountChangedNotification;
- (void)initialize:(NSString * _Nonnull)appKey secret:(NSString * _Nonnull)secret completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion SWIFT_METHOD_FAMILY(none);
- (void)logout:(void (^ _Nullable)(NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI21AppFriendsUserManager")
@interface AppFriendsUserManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AppFriendsUserManager * _Nonnull sharedInstance;)
+ (AppFriendsUserManager * _Nonnull)sharedInstance;
- (void)followUser:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)unfollowUser:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)blockUser:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)unblockUser:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)fetchFollowers:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)fetchFollowings:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)searchUser:(NSString * _Nonnull)query completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)fetchUserFriends:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)updateUserInfo:(NSString * _Nonnull)userID userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (void)fetchUserInfo:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(id _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/**
  Make sure you use  “[weak self] (gesture) in” if you are using the keyword self inside the closure or there might be a memory leak
*/
SWIFT_CLASS("_TtC12AppFriendsUI14BlockLongPress")
@interface BlockLongPress : UILongPressGestureRecognizer
- (nonnull instancetype)initWithTarget:(id _Nullable)target action:(SEL _Nullable)action SWIFT_UNAVAILABLE;
- (void)didLongPressed:(UILongPressGestureRecognizer * _Nonnull)longPress;
@end


/**
  Make sure you use  “[weak self] (gesture) in” if you are using the keyword self inside the closure or there might be a memory leak
*/
SWIFT_CLASS("_TtC12AppFriendsUI8BlockPan")
@interface BlockPan : UIPanGestureRecognizer
- (nonnull instancetype)initWithTarget:(id _Nullable)target action:(SEL _Nullable)action SWIFT_UNAVAILABLE;
- (void)didPan:(UIPanGestureRecognizer * _Nonnull)pan;
@end


/**
  Make sure you use  “[weak self] (gesture) in” if you are using the keyword self inside the closure or there might be a memory leak
*/
SWIFT_CLASS("_TtC12AppFriendsUI10BlockPinch")
@interface BlockPinch : UIPinchGestureRecognizer
- (nonnull instancetype)initWithTarget:(id _Nullable)target action:(SEL _Nullable)action SWIFT_UNAVAILABLE;
- (void)didPinch:(UIPinchGestureRecognizer * _Nonnull)pinch;
@end


/**
  Make sure you use  “[weak self] (gesture) in” if you are using the keyword self inside the closure or there might be a memory leak
*/
SWIFT_CLASS("_TtC12AppFriendsUI10BlockSwipe")
@interface BlockSwipe : UISwipeGestureRecognizer
- (nonnull instancetype)initWithTarget:(id _Nullable)target action:(SEL _Nullable)action SWIFT_UNAVAILABLE;
- (void)didSwipe:(UISwipeGestureRecognizer * _Nonnull)swipe;
@end


/**
  Make sure you use  “[weak self] (gesture) in” if you are using the keyword self inside the closure or there might be a memory leak
*/
SWIFT_CLASS("_TtC12AppFriendsUI8BlockTap")
@interface BlockTap : UITapGestureRecognizer
- (nonnull instancetype)initWithTarget:(id _Nullable)target action:(SEL _Nullable)action SWIFT_UNAVAILABLE;
- (void)didTap:(UITapGestureRecognizer * _Nonnull)tap;
@end


SWIFT_CLASS("_TtC12AppFriendsUI15ChannelsManager")
@interface ChannelsManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ChannelsManager * _Nonnull sharedInstance;)
+ (ChannelsManager * _Nonnull)sharedInstance;
- (void)fetchChannelInfo:(NSString * _Nonnull)channelID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI16CoreStoreManager")
@interface CoreStoreManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CoreStoreManager * _Nonnull sharedInstance;)
+ (CoreStoreManager * _Nonnull)sharedInstance;
- (void)initialize:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion SWIFT_METHOD_FAMILY(none);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDictionary;
@protocol DialogsManagerDelegate;

SWIFT_CLASS("_TtC12AppFriendsUI14DialogsManager")
@interface DialogsManager : NSObject <HCSDKCoreEventsDelegate>
@property (nonatomic, weak) id <DialogsManagerDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DialogsManager * _Nonnull sharedInstance;)
+ (DialogsManager * _Nonnull)sharedInstance;
@property (nonatomic) NSInteger totalUnreadMessages;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kEventStartTyping;)
+ (NSString * _Nonnull)kEventStartTyping;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kEventStopTyping;)
+ (NSString * _Nonnull)kEventStopTyping;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)initializeDialog:(NSArray<NSString *> * _Nonnull)userIDs dialogType:(NSString * _Nonnull)dialogType dialogTitle:(NSString * _Nullable)dialogTitle customJSON:(NSDictionary * _Nullable)customJSON pushData:(NSString * _Nullable)pushData completion:(void (^ _Nullable)(NSString * _Nullable, NSError * _Nullable))completion SWIFT_METHOD_FAMILY(none);
- (NSArray<NSString *> * _Nullable)memberIDsInDialog:(NSString * _Nonnull)dialogID;
- (void)getTotalUnreadMessageCount:(void (^ _Nonnull)(NSInteger))completion;
- (void)startTyping:(NSString * _Nonnull)dialogID dialogType:(NSString * _Nonnull)dialogType;
- (void)endTyping:(NSString * _Nonnull)dialogID dialogType:(NSString * _Nonnull)dialogType;
- (void)updateDialogCustomData:(NSString * _Nonnull)dialogID customData:(NSString * _Nonnull)customData completion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)updateDialogName:(NSString * _Nonnull)dialogID dialogName:(NSString * _Nonnull)dialogName completion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)fetchDialogInfo:(NSString * _Nonnull)dialogID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)addMembersToDialog:(NSString * _Nonnull)dialogID members:(NSArray<NSString *> * _Nonnull)newMembers completion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)leaveGroupDialog:(NSString * _Nonnull)dialogID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/**
  Getting the list of dialogs
  \param completion complete block, invoked when the request is completed

*/
- (void)fetchDialogs:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)muteDialog:(NSString * _Nonnull)dialogID muted:(BOOL)muted completion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)dialogEventReceived:(NSString * _Nonnull)dialogID eventName:(NSString * _Nonnull)eventName customData:(NSString * _Nonnull)customData;
@end


SWIFT_PROTOCOL("_TtP12AppFriendsUI22DialogsManagerDelegate_")
@protocol DialogsManagerDelegate
@optional
- (void)didUpdateTypingStatus:(NSString * _Nonnull)dialogID userName:(NSString * _Nonnull)userName typing:(BOOL)typing;
- (void)didChangeDialogName:(NSString * _Nonnull)newName;
@end

enum MessageReceiptStatus : NSInteger;

SWIFT_PROTOCOL("_TtP12AppFriendsUI24MessagingManagerDelegate_")
@protocol MessagingManagerDelegate
@optional
- (void)didUpdateMessageReceiptStatus:(NSString * _Nonnull)dialogID messageID:(NSString * _Nonnull)messageID byUserID:(NSString * _Nonnull)byUserID status:(enum MessageReceiptStatus)status;
@end

@class HCChatTableViewCell;

SWIFT_PROTOCOL("_TtP12AppFriendsUI27HCChatTableViewCellDelegate_")
@protocol HCChatTableViewCellDelegate
- (void)attachmentTapped:(HCChatTableViewCell * _Nonnull)cell;
- (void)avatarTapped:(HCChatTableViewCell * _Nonnull)cell;
- (void)failedButtonTapped:(HCChatTableViewCell * _Nonnull)cell;
- (void)linkTapped:(HCChatTableViewCell * _Nonnull)cell url:(NSURL * _Nonnull)url;
@end

@class NSCoder;
@class HCChatDialog;
@class UITableView;
@class UIImage;
@class UITextView;
@class UIColor;
@class UITableViewCell;
@class UIImagePickerController;
@class UIScrollView;
@class UIGestureRecognizer;
@class UICollectionViewLayout;
@class NSBundle;

SWIFT_CLASS("_TtC12AppFriendsUI24HCBaseChatViewController")
@interface HCBaseChatViewController : SLKTextViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, HCChatTableViewCellDelegate, MessagingManagerDelegate, DialogsManagerDelegate>
@property (nonatomic) BOOL showUserName;
@property (nonatomic) BOOL showCurrentUserNamePerMessage;
@property (nonatomic, copy) NSString * _Nullable currentUserID;
@property (nonatomic, copy) NSString * _Nonnull _dialogType;
@property (nonatomic, copy) NSString * _Nonnull _dialogID;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTableViewStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (HCChatDialog * _Nullable)currentDialog;
- (void)updateTitle;
@property (nonatomic, readonly, strong) UITableView * _Nonnull tableView;
/**
  Action when right button, which is the send button, is triggered
  \param sender the send button

*/
- (void)didPressRightButton:(id _Nullable)sender;
- (void)didPressLeftButton:(id _Nullable)sender;
- (UIImage * _Nonnull)avatarImage;
- (void)pickImageToSend;
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (void)didUpdateTypingStatus:(NSString * _Nonnull)dialogID userName:(NSString * _Nonnull)userName typing:(BOOL)typing;
- (void)didChangeDialogName:(NSString * _Nonnull)newName;
- (BOOL)isSentMessageAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (HCChatTableViewCell * _Nonnull)messagingCellAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSDictionary<NSString *, id> * _Nonnull)messagingCellAttributes:(UIColor * _Nonnull)messageColor;
- (NSDictionary<NSString *, id> * _Nonnull)systemMessagingCellAttributes;
- (NSDictionary<NSString *, id> * _Nonnull)linkTextAttributes;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didEndDisplayingCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSIndexPath * _Nullable)tableView:(UITableView * _Nonnull)tableView willSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *, id> * _Nonnull)info;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)fetchMoreMessages;
- (void)deleteMessageAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)resendMessageAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)didSendTextMessage;
- (void)didSendImageMessage;
- (void)didSendVideoMessage;
- (void)linkTapped:(HCChatTableViewCell * _Nonnull)cell url:(NSURL * _Nonnull)url;
- (void)messageImageTapped:(NSString * _Nonnull)imageURL;
- (void)messageVideoTapped:(NSString * _Nonnull)videoURL;
- (void)failedButtonTapped:(HCChatTableViewCell * _Nonnull)cell;
- (void)avatarTapped:(HCChatTableViewCell * _Nonnull)cell;
- (void)attachmentTapped:(HCChatTableViewCell * _Nonnull)cell;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer;
- (void)showProgress:(float)progress message:(NSString * _Nonnull)message;
- (void)showLoading:(NSString * _Nullable)message;
- (void)showErrorWithMessage:(NSString * _Nullable)message;
- (void)showSuccessWithMessage:(NSString * _Nullable)message;
- (void)hideHUD;
- (nonnull instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * _Nonnull)layout SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithScrollView:(UIScrollView * _Nonnull)scrollView SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface HCBaseChatViewController (SWIFT_EXTENSION(AppFriendsUI)) <AVAssetResourceLoaderDelegate>
@end


@interface HCBaseChatViewController (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface HCBaseChatViewController (SWIFT_EXTENSION(AppFriendsUI))
@end


SWIFT_CLASS("_TtC12AppFriendsUI20HCBaseViewController")
@interface HCBaseViewController : UIViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)showProgress:(float)progress message:(NSString * _Nonnull)message;
- (void)showLoading:(NSString * _Nullable)message;
- (void)showErrorWithMessage:(NSString * _Nullable)message;
- (void)showSuccessWithMessage:(NSString * _Nullable)message;
- (void)hideHUD;
@end

@class NSManagedObjectContext;
@class NSEntityDescription;

SWIFT_CLASS("_TtC12AppFriendsUI10_HCChannel")
@interface _HCChannel : NSManagedObject
+ (NSString * _Nonnull)entityName;
+ (NSEntityDescription * _Nullable)entity:(NSManagedObjectContext * _Nonnull)managedObjectContext;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithManagedObjectContext:(NSManagedObjectContext * _Nonnull)managedObjectContext;
@property (nonatomic, copy) NSString * _Nullable channelID;
@property (nonatomic, copy) NSString * _Nullable customData;
@property (nonatomic, copy) NSString * _Nullable title;
@end


SWIFT_CLASS_NAMED("HCChannel")
@interface HCChannel : _HCChannel
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI27HCChannelChatViewController")
@interface HCChannelChatViewController : HCBaseChatViewController
- (nonnull instancetype)initWithDialog:(NSString * _Nonnull)dialog OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
@end


SWIFT_CLASS("_TtC12AppFriendsUI22HCChannelTableViewCell")
@interface HCChannelTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI28HCChannelsListViewController")
@interface HCChannelsListViewController : HCBaseViewController <UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate>
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class HCGroupCreatorViewController;

SWIFT_PROTOCOL("_TtP12AppFriendsUI36HCGroupCreatorViewControllerDelegate_")
@protocol HCGroupCreatorViewControllerDelegate
- (void)usersSelected:(NSArray<NSString *> * _Nonnull)users;
- (void)closeButtonTapped:(HCGroupCreatorViewController * _Nonnull)selectVC;
@end

@class SMSegmentView;

SWIFT_CLASS("_TtC12AppFriendsUI29HCChatContainerViewController")
@interface HCChatContainerViewController : HCBaseViewController <HCGroupCreatorViewControllerDelegate>
@property (nonatomic, weak) SMSegmentView * _Null_unspecified _segmentView;
- (nonnull instancetype)initWithTabs:(NSArray<NSString *> * _Nonnull)tabs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)close;
- (void)moreButtonTapped;
- (void)addSegmentedControler;
- (void)switchTabs:(SMSegmentView * _Nonnull)segmentView;
- (void)displayChannelsList;
- (void)displayDialogsList;
- (void)displayContactsList;
- (void)removeVC:(UIViewController * _Nullable)contentVC;
- (void)usersSelected:(NSArray<NSString *> * _Nonnull)users;
- (void)closeButtonTapped:(HCGroupCreatorViewController * _Nonnull)selectVC;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC12AppFriendsUI17HCChatContentView")
@interface HCChatContentView : UITextView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
@class NSSet;

SWIFT_CLASS("_TtC12AppFriendsUI13_HCChatDialog")
@interface _HCChatDialog : NSManagedObject
+ (NSString * _Nonnull)entityName;
+ (NSEntityDescription * _Nullable)entity:(NSManagedObjectContext * _Nonnull)managedObjectContext;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithManagedObjectContext:(NSManagedObjectContext * _Nonnull)managedObjectContext;
@property (nonatomic, copy) NSDate * _Nullable createTime;
@property (nonatomic, copy) NSString * _Nullable customData;
@property (nonatomic, copy) NSString * _Nullable dialogID;
@property (nonatomic, copy) NSDate * _Nullable lastMessageReadTime;
@property (nonatomic, copy) NSString * _Nullable lastMessageText;
@property (nonatomic, copy) NSDate * _Nullable lastMessageTime;
@property (nonatomic, strong) NSNumber * _Nullable muted;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSNumber * _Nullable unreadMessages;
@property (nonatomic, strong) NSSet * _Nonnull members;
@end


SWIFT_CLASS_NAMED("HCChatDialog")
@interface HCChatDialog : _HCChatDialog
- (NSString * _Nonnull)defaultDialogName;
- (NSArray<NSString *> * _Nonnull)memberIDs;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSLayoutConstraint;
@class UILabel;
@class UIImageView;
@class UIButton;

SWIFT_CLASS("_TtC12AppFriendsUI19HCChatTableViewCell")
@interface HCChatTableViewCell : UITableViewCell <UIScrollViewDelegate, UITextViewDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellTopMargin;)
+ (CGFloat)kChatCellTopMargin;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellBottomMargin;)
+ (CGFloat)kChatCellBottomMargin;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellLeftMargin;)
+ (CGFloat)kChatCellLeftMargin;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellRightMargin;)
+ (CGFloat)kChatCellRightMargin;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellMinimumHeight;)
+ (CGFloat)kChatCellMinimumHeight;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellAvatarHeight;)
+ (CGFloat)kChatCellAvatarHeight;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kImageCellHeight;)
+ (CGFloat)kImageCellHeight;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kDateLabelHeight;)
+ (CGFloat)kDateLabelHeight;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kSeenByLabelHeight;)
+ (CGFloat)kSeenByLabelHeight;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kNewMessageLineHeight;)
+ (CGFloat)kNewMessageLineHeight;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellSystemMessageHorizontalMargin;)
+ (CGFloat)kChatCellSystemMessageHorizontalMargin;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellSystemMessageVerticalMarginTop;)
+ (CGFloat)kChatCellSystemMessageVerticalMarginTop;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat kChatCellSystemMessageVerticalMarginBottom;)
+ (CGFloat)kChatCellSystemMessageVerticalMarginBottom;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Nullable messageWidthConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Nullable messageLeadingConstraint;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Nullable messageTrailingConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Nullable userNameHeightConstraint;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable userNameLabel;
@property (nonatomic, weak) IBOutlet HCChatContentView * _Nullable messageContentLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable seenByLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable dateLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable timeLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Nullable userAvatarImageView;
@property (nonatomic, weak) IBOutlet UIImageView * _Nullable contentBackgroundBubble;
@property (nonatomic, weak) IBOutlet UIImageView * _Nullable contentImageView;
@property (nonatomic, weak) IBOutlet UIButton * _Nullable failedButton;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable videoPlayIcon;
@property (nonatomic, weak) id <HCChatTableViewCellDelegate> _Nullable delegate;
@property (nonatomic, copy) NSDate * _Nullable messageTime;
@property (nonatomic) BOOL isSentMessageCell;
- (void)awakeFromNib;
- (void)updateTime;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC12AppFriendsUI20HCContactSelectField")
@interface HCContactSelectField : CLTokenInputView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI22HCContactTableViewCell")
@interface HCContactTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI24HCContactsViewController")
@interface HCContactsViewController : HCBaseViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIBarButtonItem;

SWIFT_CLASS("_TtC12AppFriendsUI26HCDialogChatViewController")
@interface HCDialogChatViewController : HCBaseChatViewController <HCGroupCreatorViewControllerDelegate>
- (nonnull instancetype)initWithDialog:(NSString * _Nonnull)dialog OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTableViewStyle:(UITableViewStyle)tableViewStyle OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (UIBarButtonItem * _Nullable)rightNavigationItem;
- (void)settingButtonTapped;
- (void)didUpdateDialog:(NSNotification * _Nonnull)notification;
- (void)usersSelected:(NSArray<NSString *> * _Nonnull)users;
- (void)closeButtonTapped:(HCGroupCreatorViewController * _Nonnull)selectVC;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC12AppFriendsUI32HCDialogMemberCollectionViewCell")
@interface HCDialogMemberCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified userAvatar;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified userNameLabel;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;
@class UIView;
@class UISwitch;

SWIFT_CLASS("_TtC12AppFriendsUI29HCDialogSettingViewController")
@interface HCDialogSettingViewController : HCBaseViewController <UIScrollViewDelegate, UITableViewDataSource, UICollectionViewDelegate, UICollectionViewDataSource, UITableViewDelegate>
@property (nonatomic, copy) NSString * _Nullable _dialogID;
@property (nonatomic, copy) NSString * _Nullable _dialogType;
@property (nonatomic, copy) NSString * _Nullable _dialogName;
@property (nonatomic, strong) NSNumber * _Nullable _dialogMembersCount;
@property (nonatomic, strong) UITableView * _Nullable _tableView;
@property (nonatomic, strong) UICollectionView * _Nullable _membersCollectionView;
- (nonnull instancetype)initWithDialog:(NSString * _Nonnull)dialog OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)updateDialogName;
- (HCChatDialog * _Nullable)currentDialog;
- (UIView * _Nonnull)createMembersListView;
- (UITableView * _Nonnull)createTableView;
- (void)registerTableCells;
- (UIView * _Nonnull)tableFooterView;
- (UIView * _Nonnull)tableSectionView:(NSInteger)section;
- (void)closeView;
- (void)didLeaveDialog;
- (void)leaveDialog;
- (void)muteDialog:(UISwitch * _Nonnull)toggle;
- (void)membersRowTapped;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)isMuteConversationRow:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)isDialogNameRow:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)isMembersRow:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)didClickOnMemberWithMemberID:(NSString * _Nonnull)userID;
- (void)fillMemberCell:(HCDialogMemberCollectionViewCell * _Nonnull)cell atIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)reloadMembersRow;
- (void)didUpdateDialog:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class HCTopAlignedContentLabel;

SWIFT_CLASS("_TtC12AppFriendsUI21HCDialogTableViewCell")
@interface HCDialogTableViewCell : SESlideTableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified dialogAvatarImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified userNameLabel;
@property (nonatomic, weak) IBOutlet HCTopAlignedContentLabel * _Null_unspecified lastMessageLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lastMessageTimeLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified badgeView;
- (void)awakeFromNib;
- (void)addRightButtonWithText:(NSString * _Null_unspecified)text textColor:(UIColor * _Null_unspecified)textColor backgroundColor:(UIColor * _Null_unspecified)backgroundColor;
- (void)addRightButtonWithImage:(UIImage * _Null_unspecified)image backgroundColor:(UIColor * _Null_unspecified)backgroundColor;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)hideBadge:(BOOL)hide;
- (null_unspecified instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSPredicate;

SWIFT_CLASS("_TtC12AppFriendsUI27HCDialogsListViewController")
@interface HCDialogsListViewController : HCBaseViewController <SESlideTableViewCellDelegate, UITableViewDelegate, UIScrollViewDelegate, UITableViewDataSource>
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, copy) NSString * _Nullable currentUserID;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (NSPredicate * _Nonnull)dialogsQuery;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)slideTableViewCell:(SESlideTableViewCell * _Null_unspecified)cell didTriggerRightButton:(NSInteger)buttonIndex;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class CLToken;

SWIFT_CLASS("_TtC12AppFriendsUI28HCGroupCreatorViewController")
@interface HCGroupCreatorViewController : HCContactsViewController <CLTokenInputViewDelegate>
@property (nonatomic, weak) id <HCGroupCreatorViewControllerDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable dialogID;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)tokenInputView:(CLTokenInputView * _Nonnull)view didAddToken:(CLToken * _Nonnull)token;
- (void)tokenInputView:(CLTokenInputView * _Nonnull)view didRemoveToken:(CLToken * _Nonnull)token;
- (void)tokenInputView:(CLTokenInputView * _Nonnull)view didChangeHeightTo:(CGFloat)height;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC12AppFriendsUI26HCImageModalViewController")
@interface HCImageModalViewController : HCBaseViewController <UIScrollViewDelegate>
- (nonnull instancetype)initWithUrl:(NSString * _Nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (UIView * _Nullable)viewForZoomingInScrollView:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndZooming:(UIScrollView * _Nonnull)scrollView withView:(UIView * _Nullable)view atScale:(CGFloat)scale;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12AppFriendsUI10_HCMessage")
@interface _HCMessage : NSManagedObject
+ (NSString * _Nonnull)entityName;
+ (NSEntityDescription * _Nullable)entity:(NSManagedObjectContext * _Nonnull)managedObjectContext;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithManagedObjectContext:(NSManagedObjectContext * _Nonnull)managedObjectContext;
@property (nonatomic, copy) NSString * _Nullable channelID;
@property (nonatomic, copy) NSString * _Nullable customData;
@property (nonatomic, copy) NSString * _Nullable dialogID;
@property (nonatomic, strong) NSNumber * _Nullable failed;
@property (nonatomic, strong) NSNumber * _Nullable handled;
@property (nonatomic, copy) NSString * _Nullable messageID;
@property (nonatomic, copy) NSString * _Nullable messageType;
@property (nonatomic, strong) id _Nullable metadata;
@property (nonatomic, strong) NSNumber * _Nullable read;
@property (nonatomic, strong) NSNumber * _Nullable receiptRequired;
@property (nonatomic, copy) NSDate * _Nullable receiveTime;
@property (nonatomic, copy) NSString * _Nullable senderAvatar;
@property (nonatomic, copy) NSString * _Nullable senderID;
@property (nonatomic, copy) NSString * _Nullable senderName;
@property (nonatomic, copy) NSDate * _Nullable sentTime;
@property (nonatomic, copy) NSString * _Nullable tempID;
@property (nonatomic, copy) NSString * _Nullable text;
@end


SWIFT_CLASS_NAMED("HCMessage")
@interface HCMessage : _HCMessage
+ (NSDictionary * _Nonnull)messageJSONFromMessageWithMessageObject:(HCMessage * _Nonnull)message;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI19HCMessageAttachment")
@interface HCMessageAttachment : NSObject
+ (HCMessageAttachment * _Nullable)getAttachmentFromMessageWithDataString:(NSString * _Nonnull)customData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, HCMessageAttachmentType) {
  HCMessageAttachmentTypeImage = 0,
  HCMessageAttachmentTypeVideo = 1,
  HCMessageAttachmentTypeGif = 2,
};

typedef SWIFT_ENUM(NSInteger, HCSideDirection) {
  HCSideDirectionLeft = 0,
  HCSideDirectionRight = 1,
};

@protocol UIViewControllerContextTransitioning;
@protocol UIViewControllerInteractiveTransitioning;

SWIFT_CLASS("_TtC12AppFriendsUI19HCSidePanelAnimator")
@interface HCSidePanelAnimator : NSObject <UIViewControllerAnimatedTransitioning, UIViewControllerTransitioningDelegate>
@property (nonatomic) enum HCSideDirection slideDirection;
@property (nonatomic) BOOL presenting;
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> _Nullable)transitionContext;
- (void)animateTransition:(id <UIViewControllerContextTransitioning> _Nonnull)transitionContext;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed;
- (id <UIViewControllerInteractiveTransitioning> _Nullable)interactionControllerForDismissal:(id <UIViewControllerAnimatedTransitioning> _Nonnull)animator;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI25HCSidePanelViewController")
@interface HCSidePanelViewController : UIViewController
- (nonnull instancetype)initWithAnimator:(HCSidePanelAnimator * _Nonnull)animator contentVC:(UIViewController * _Nonnull)contentVC OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12AppFriendsUI24HCTopAlignedContentLabel")
@interface HCTopAlignedContentLabel : UILabel
- (void)drawTextInRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI7_HCUser")
@interface _HCUser : NSManagedObject
+ (NSString * _Nonnull)entityName;
+ (NSEntityDescription * _Nullable)entity:(NSManagedObjectContext * _Nonnull)managedObjectContext;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithManagedObjectContext:(NSManagedObjectContext * _Nonnull)managedObjectContext;
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, strong) NSNumber * _Nullable blocked;
@property (nonatomic, copy) NSString * _Nullable customData;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, strong) id _Nullable followers;
@property (nonatomic, strong) id _Nullable following;
@property (nonatomic, strong) id _Nullable friends;
@property (nonatomic, copy) NSString * _Nullable userID;
@property (nonatomic, copy) NSString * _Nullable userName;
@property (nonatomic, strong) NSSet * _Nonnull dialogs;
@end


SWIFT_CLASS_NAMED("HCUser")
@interface HCUser : _HCUser
+ (HCUser * _Nullable)currentUser;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class UISearchBar;

SWIFT_CLASS("_TtC12AppFriendsUI26HCUserSearchViewController")
@interface HCUserSearchViewController : HCBaseViewController <UIBarPositioningDelegate, UITableViewDataSource, UISearchBarDelegate, UIScrollViewDelegate, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UISearchBar * _Null_unspecified searchBar;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (HCUser * _Nullable)userAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)searchBarSearchButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI7HCUtils")
@interface HCUtils : NSObject
+ (NSString * _Nonnull)createUniqueID;
+ (NSString * _Nonnull)jsonStringFromDictionary;
+ (NSDictionary<NSString *, id> * _Nullable)dictionaryFromJsonString:(NSString * _Nonnull)text;
+ (UIImage * _Nullable)imageInHCBundle:(NSString * _Nonnull)name;
+ (NSBundle * _Nullable)xibBundle;
+ (NSBundle * _Nullable)coreDataBundle;
+ (NSBundle * _Nullable)appFriendsBundle;
+ (void)registerNib:(UITableView * _Nonnull)tableView nibName:(NSString * _Nonnull)nibName forCellReuseIdentifier:(NSString * _Nonnull)identifier;
+ (NSString * _Nonnull)messageTimestampString:(NSDate * _Nullable)date;
+ (NSString * _Nonnull)messageDateLabelString:(NSDate * _Nullable)date;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12AppFriendsUI17HCVideoAttachment")
@interface HCVideoAttachment : HCMessageAttachment
+ (HCVideoAttachment * _Nullable)getAttachmentFromMessageWithDataString:(NSString * _Nonnull)customData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MessageReceiptStatus) {
  MessageReceiptStatusUnknown = 0,
  MessageReceiptStatusReceived = 1,
  MessageReceiptStatusRead = 2,
};


SWIFT_CLASS("_TtC12AppFriendsUI16MessagingManager")
@interface MessagingManager : NSObject <HCSDKCoreSyncDelegate>
@property (nonatomic, weak) id <MessagingManagerDelegate> _Nullable delegate;
@property (nonatomic, readonly, copy) NSString * _Nonnull action_dialog;
@property (nonatomic, readonly, copy) NSString * _Nonnull action_message;
@property (nonatomic, readonly, copy) NSString * _Nonnull action_type_receive_receipt;
@property (nonatomic, readonly, copy) NSString * _Nonnull action_type_read_receipt;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MessagingManager * _Nonnull sharedInstance;)
+ (MessagingManager * _Nonnull)sharedInstance;
+ (void)startReceivingMessage;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)messagesReceived:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)messages;
- (NSString * _Nullable)lastReceivedMessageIDInChannel:(NSString * _Nonnull)channelID;
- (void)postMessageReceiptWithTempID:(NSString * _Nonnull)messageTempID dialogID:(NSString * _Nonnull)dialogID senderID:(NSString * _Nonnull)senderID receiptStatus:(enum MessageReceiptStatus)receiptStatus;
- (NSDictionary * _Nonnull)createTextMessageJSON:(NSString * _Nonnull)text dialogID:(NSString * _Nonnull)dialogID;
- (NSDictionary * _Nonnull)createVideoMessageJSON:(NSString * _Nonnull)videoStreamURL thumbnail:(NSString * _Nonnull)thumbnail dialogID:(NSString * _Nonnull)dialogID;
- (NSDictionary * _Nonnull)createImageMessageJSON:(NSString * _Nonnull)url dialogID:(NSString * _Nonnull)dialogID;
- (NSDictionary * _Nonnull)createSenderJSON;
- (NSDictionary * _Nonnull)createImagePayloadJSON:(NSString * _Nonnull)imageURL;
- (NSDictionary * _Nonnull)createVideoPayloadJSON:(NSString * _Nonnull)videoStreamURL thumbnail:(NSString * _Nonnull)thumbnail;
- (void)failMessage:(NSString * _Nonnull)tempID;
@end



@interface NSDictionary (SWIFT_EXTENSION(AppFriendsUI))
- (NSString * _Nonnull)toString;
@end

@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC12AppFriendsUI9SMSegment")
@interface SMSegment : UIView
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) UIImage * _Nullable onSelectionImage;
@property (nonatomic, strong) UIImage * _Nullable offSelectionImage;
@property (nonatomic, readonly) NSInteger index;
@property (nonatomic, readonly) BOOL isSelected;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12AppFriendsUI13SMSegmentView")
@interface SMSegmentView : UIControl
@property (nonatomic, strong) UIColor * _Nonnull dividerColour;
@property (nonatomic) CGFloat dividerWidth;
@property (nonatomic) NSInteger selectedSegmentIndex;
@property (nonatomic, readonly) NSInteger numberOfSegments;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)addSegmentWithTitle:(NSString * _Nullable)title onSelectionImage:(UIImage * _Nullable)onSelectionImage offSelectionImage:(UIImage * _Nullable)offSelectionImage;
- (void)insertSegmentWithTitle:(NSString * _Nullable)title onSelectionImage:(UIImage * _Nullable)onSelectionImage offSelectionImage:(UIImage * _Nullable)offSelectionImage index:(NSInteger)index;
- (void)removeSegmentAtIndex:(NSInteger)index;
- (void)layoutSubviews;
- (void)drawRect:(CGRect)rect;
@end


@interface NSTimer (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIBarButtonItem (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIButton (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIColor (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIFont (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIImage (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIImage (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UILabel (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UILabel (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@property (nonatomic, copy) NSString * _Nullable badge;
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIView (SWIFT_EXTENSION(AppFriendsUI))
@end


@interface UIViewController (SWIFT_EXTENSION(AppFriendsUI))
@end




@interface _HCChatDialog (SWIFT_EXTENSION(AppFriendsUI))
@end




@interface _HCUser (SWIFT_EXTENSION(AppFriendsUI))
@end

#pragma clang diagnostic pop
