# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppFriendsChatSample' do
    use_frameworks!

    # Pods for AppFriendsChatSample
    pod 'AppFriendsUI', :git => 'https://github.com/Hacknocraft/AppFriendsUI.git', :tag => '1.1.5'
    pod 'AppFriendsCore', :git => 'https://github.com/Hacknocraft/AppFriendsCore.git', :tag => '1.0.3'

    # pods for testing distribution
    pod 'Fabric'
    pod 'Crashlytics'

    # pods for push notification
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'EZSwiftExtensions', '~> 1.8'

end
