# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppFriendsChatSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppFriendsChatSample
  #pod 'AppFriendsUI', :path => '../../'
  pod 'AppFriendsUI', :git => 'https://github.com/Hacknocraft/AppFriendsUI.git', :branch => 'swift3.0'
  pod 'AppFriendsCore', :git => 'https://github.com/laeroah/AppFriendsCoreFramework.git', :branch => 'swift3.0'
  pod 'CoreStore', :git => 'https://github.com/AppFriendsMe/CoreStore.git', :branch => 'swift3_develop'

end
