# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppFriendsChatSample' do
    use_frameworks!

    # Pods for AppFriendsChatSample
    pod 'AppFriendsUI', :git => 'https://github.com/Hacknocraft/AppFriendsUI.git', :tag => '1.0.25'
    pod 'AppFriendsCore', :git => 'https://github.com/Hacknocraft/AppFriendsCore.git', :tag => '0.1.66'
    pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'swift3_develop'

    # pods for testing distribution
    pod 'Fabric'
    pod 'Crashlytics'

    # pods for push notification
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'EZSwiftExtensions', '~> 1.7'

end
